# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pgw.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pgw.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpgw.proto\x12\x03PGW\"J\n\x0bSNMPRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0b\n\x03oid\x18\x02 \x01(\t\x12\x11\n\tcommunity\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\x05\"-\n\x0cSNMPResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t23\n\x04SNMP\x12+\n\x04Poll\x12\x10.PGW.SNMPRequest\x1a\x11.PGW.SNMPResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pgw_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SNMPREQUEST']._serialized_start=18
  _globals['_SNMPREQUEST']._serialized_end=92
  _globals['_SNMPRESPONSE']._serialized_start=94
  _globals['_SNMPRESPONSE']._serialized_end=139
  _globals['_SNMP']._serialized_start=141
  _globals['_SNMP']._serialized_end=192
# @@protoc_insertion_point(module_scope)
